//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CmsResources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string About_Us {
            get {
                return ResourceManager.GetString("About Us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company was founded in 1994 by a group of highly competent &amp; experienced professionals in the Travel and Tourism domain. Since its inception, Al Ketbi Travel has consistently delivered top quality services that are meeting/exceeding customer expectations.
        ///
        ///In the light of the above, Al Ketbi Travel had broadened its array of services to comprise 6 main areas: Reservations, Ticketing, Tour Packages, Travel Insurance, Hotel Booking, Desert Safari and Dhow Cruise..
        /// </summary>
        public static string AboutUsContent {
            get {
                return ResourceManager.GetString("AboutUsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access special offers and unique experiences..
        /// </summary>
        public static string Access_special_offers_and_unique_experiences_ {
            get {
                return ResourceManager.GetString("Access special offers and unique experiences.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abu Dhabi, Al Bateen W-10, Al Faskar Street, Al Khalidiya Tower, Minzaanin Floor.
        /// </summary>
        public static string adddress {
            get {
                return ResourceManager.GetString("adddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always Available.
        /// </summary>
        public static string Always_Available {
            get {
                return ResourceManager.GetString("Always Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings are subject to availability and confirmation. Al Ketbi Travel reserves the right to cancel or modify bookings that violate
        ///      our terms..
        /// </summary>
        public static string BC1 {
            get {
                return ResourceManager.GetString("BC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking and Service Policies.
        /// </summary>
        public static string Booking_and_Service_Policies {
            get {
                return ResourceManager.GetString("Booking and Service Policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Conditions:.
        /// </summary>
        public static string Booking_Conditions_ {
            get {
                return ResourceManager.GetString("Booking Conditions:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Process:.
        /// </summary>
        public static string Booking_Process_ {
            get {
                return ResourceManager.GetString("Booking Process:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users can book services through our website by following the provided instructions. Bookings are subject to availability and confirmation..
        /// </summary>
        public static string BP1 {
            get {
                return ResourceManager.GetString("BP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users are responsible for understanding and agreeing to any specific conditions associated with booked services. Any additional requirements will be communicated during the booking process..
        /// </summary>
        public static string BP2 {
            get {
                return ResourceManager.GetString("BP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Philosophy:.
        /// </summary>
        public static string Business_Philosophy_ {
            get {
                return ResourceManager.GetString("Business Philosophy:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To strive for worldwide excellence in its travel and tourism business practices, following a three-pronged approach:
        ///
        ///Foster a focused, proactive, professional and innovative environment in the organization and to enhance owners value and customer satisfaction.
        ///
        ///Empower the local and regional travel and tourism fraternity with business intelligence to facilitate informed decision making and gain operational efficiency through its enterprise products, services and solutions.
        ///
        ///Expand vertically and hori [rest of string was truncated]&quot;;.
        /// </summary>
        public static string BusinessContent {
            get {
                return ResourceManager.GetString("BusinessContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © 2023 Al Ketbi Travels Company. All rights reserved.
        /// </summary>
        public static string CC {
            get {
                return ResourceManager.GetString("CC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Al Ketbi Travel website. How can we help you?.
        /// </summary>
        public static string chWlcmMsg {
            get {
                return ResourceManager.GetString("chWlcmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ci {
            get {
                return ResourceManager.GetString("ci", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Ketbi Travels Company. All rights reserved.
        /// </summary>
        public static string company {
            get {
                return ResourceManager.GetString("company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Ketbi Travels.
        /// </summary>
        public static string compName {
            get {
                return ResourceManager.GetString("compName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For any inquiries or concerns regarding our services or policies, please contactus at:.
        /// </summary>
        public static string Contact_Information {
            get {
                return ResourceManager.GetString("Contact Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customized for You.
        /// </summary>
        public static string Customized_for_You {
            get {
                return ResourceManager.GetString("Customized for You", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department of the Presidential Affairs.
        /// </summary>
        public static string Department_of_the_Presidential_Affairs {
            get {
                return ResourceManager.GetString("Department of the Presidential Affairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ltr.
        /// </summary>
        public static string dir {
            get {
                return ResourceManager.GetString("dir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        public static string Email_ {
            get {
                return ResourceManager.GetString("Email:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates Falconers&apos; Club (EFC).
        /// </summary>
        public static string Emirates_Falconers__Club__EFC_ {
            get {
                return ResourceManager.GetString("Emirates Falconers\' Club (EFC)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for using Al Ketbi
        /// Travel&apos;s chat service. If you
        /// need further assistance, feel
        /// free to ask. Have a great day!.
        /// </summary>
        public static string endMSG {
            get {
                return ResourceManager.GetString("endMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusive Deals.
        /// </summary>
        public static string Exclusive_Deals {
            get {
                return ResourceManager.GetString("Exclusive Deals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertise Since 1994.
        /// </summary>
        public static string Expertise_Since_1994 {
            get {
                return ResourceManager.GetString("Expertise Since 1994", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get support anytime during your trip 24/7..
        /// </summary>
        public static string Get_support_anytime_during_your_trip_24_7_ {
            get {
                return ResourceManager.GetString("Get support anytime during your trip 24/7.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IATA Groups.
        /// </summary>
        public static string IATA_Groups {
            get {
                return ResourceManager.GetString("IATA Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information Collection:.
        /// </summary>
        public static string Information_Collection_ {
            get {
                return ResourceManager.GetString("Information Collection:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Fund for Houbara Conservation (IFHC).
        /// </summary>
        public static string International_Fund_for_Houbara_Conservation__IFHC_ {
            get {
                return ResourceManager.GetString("International Fund for Houbara Conservation (IFHC)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to arLang.svg.
        /// </summary>
        public static string langImage {
            get {
                return ResourceManager.GetString("langImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Lang?culture=ar.
        /// </summary>
        public static string langUrl {
            get {
                return ResourceManager.GetString("langUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info@alketbitravelofficial.ae.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ministry of Presidential Affairs.
        /// </summary>
        public static string Ministry_of_Presidential_Affairs {
            get {
                return ResourceManager.GetString("Ministry of Presidential Affairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mohamed Bin Zayed RaptoR FUNDS.
        /// </summary>
        public static string Mohamed_Bin_Zayed_RaptoR_FUNDS {
            get {
                return ResourceManager.GetString("Mohamed Bin Zayed RaptoR FUNDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NAJAHI Events.
        /// </summary>
        public static string NAJAHI_Events {
            get {
                return ResourceManager.GetString("NAJAHI Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National Search and Rescue Center | UAE.
        /// </summary>
        public static string National_Search_and_Rescue_Center___UAE {
            get {
                return ResourceManager.GetString("National Search and Rescue Center | UAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations:.
        /// </summary>
        public static string Observations_ {
            get {
                return ResourceManager.GetString("Observations:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our experienced team makes travel planning easy..
        /// </summary>
        public static string Our_experienced_team_makes_travel_planning_easy_ {
            get {
                return ResourceManager.GetString("Our experienced team makes travel planning easy.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over 29 years creating unforgettable trips..
        /// </summary>
        public static string Over_29_years_creating_unforgettable_trips_ {
            get {
                return ResourceManager.GetString("Over 29 years creating unforgettable trips.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personalized travel plans to match your preferences..
        /// </summary>
        public static string Personalized_travel_plans_to_match_your_preferences_ {
            get {
                return ResourceManager.GetString("Personalized travel plans to match your preferences.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone:.
        /// </summary>
        public static string Phone_ {
            get {
                return ResourceManager.GetString("Phone:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We may collect personal identification information from users in various ways, including, but not limited to, when users visit our site, register on the site, and place bookings..
        /// </summary>
        public static string PP1 {
            get {
                return ResourceManager.GetString("PP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any information provided by users will be used for the purpose of booking and improving our services. We do not share this information with third parties..
        /// </summary>
        public static string PP2 {
            get {
                return ResourceManager.GetString("PP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your privacy is important to us. This privacy policy outlines how Al Ketbi Travel collects, uses, maintains, and discloses information collected from users..
        /// </summary>
        public static string PPContent {
            get {
                return ResourceManager.GetString("PPContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string Privacy_Policy {
            get {
                return ResourceManager.GetString("Privacy Policy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prohibited Activities:.
        /// </summary>
        public static string Prohibited_Activities_ {
            get {
                return ResourceManager.GetString("Prohibited Activities:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality Assured.
        /// </summary>
        public static string Quality_Assured {
            get {
                return ResourceManager.GetString("Quality Assured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted successfully..
        /// </summary>
        public static string Sent {
            get {
                return ResourceManager.GetString("Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special promotion
        ///                    and high value
        ///                    services with major
        ///                    Airlines operating
        ///                    from UAE to all over
        ///                    the world..
        /// </summary>
        public static string serv1Cont {
            get {
                return ResourceManager.GetString("serv1Cont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airline
        ///                    Reservations.
        /// </summary>
        public static string serv1Titl {
            get {
                return ResourceManager.GetString("serv1Titl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We can provide 4 star
        ////5 star hotels or
        ///Apartment with
        ///specially designed
        ///amenities..
        /// </summary>
        public static string serv2Cont {
            get {
                return ResourceManager.GetString("serv2Cont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotel / Apartment
        ///                        Reservations.
        /// </summary>
        public static string serv2Titl {
            get {
                return ResourceManager.GetString("serv2Titl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tailor made tour
        ///packages with 5*
        ///deluxe hotels and
        ///private transfers..
        /// </summary>
        public static string serv3Cont {
            get {
                return ResourceManager.GetString("serv3Cont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxury Travel
        ///                    services.
        /// </summary>
        public static string serv3Titl {
            get {
                return ResourceManager.GetString("serv3Titl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specially designed
        ///                    honeymoon
        ///                    packages
        ///                    with exotic
        ///                    destinations..
        /// </summary>
        public static string serv4Cont {
            get {
                return ResourceManager.GetString("serv4Cont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Honeymoon
        ///                    packages.
        /// </summary>
        public static string serv4Titl {
            get {
                return ResourceManager.GetString("serv4Titl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We provide holiday
        ///                    packages with unique
        ///                    services For the
        ///                    Individual and
        ///                    Group bookings..
        /// </summary>
        public static string serv5Cont {
            get {
                return ResourceManager.GetString("serv5Cont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Packages.
        /// </summary>
        public static string serv5Titl {
            get {
                return ResourceManager.GetString("serv5Titl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Conditions:.
        /// </summary>
        public static string Service_Conditions_ {
            get {
                return ResourceManager.GetString("Service Conditions:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Description:.
        /// </summary>
        public static string Service_Description_ {
            get {
                return ResourceManager.GetString("Service Description:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Ketbi Travel provides information about travel services based in Abu Dhabi, UAE. We offer booking services for various travel experiences within the region..
        /// </summary>
        public static string srvc1 {
            get {
                return ResourceManager.GetString("srvc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users are responsible for providing accurate information during the booking process. Al Ketbi Travel reserves the right to refuse servic e to anyone for any reason at any time..
        /// </summary>
        public static string srvc2 {
            get {
                return ResourceManager.GetString("srvc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookings are subject to availability and confirmation. Al Ketbi Travel reserves the right to cancel or modify bookings that violate our terms..
        /// </summary>
        public static string srvc3 {
            get {
                return ResourceManager.GetString("srvc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Service (TOS):.
        /// </summary>
        public static string Terms_of_Service__TOS__ {
            get {
                return ResourceManager.GetString("Terms of Service (TOS):", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Services.
        /// </summary>
        public static string Terms_of_Servicess {
            get {
                return ResourceManager.GetString("Terms of Servicess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, will be contacted soon..
        /// </summary>
        public static string ThanksMSG {
            get {
                return ResourceManager.GetString("ThanksMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Al Ketbi Travel! By accessing and using our website, you agree to comply with and be bound by the following terms and conditions of use. Please read these terms carefully before using our services..
        /// </summary>
        public static string TOSContent {
            get {
                return ResourceManager.GetString("TOSContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trusted Guidance.
        /// </summary>
        public static string Trusted_Guidance {
            get {
                return ResourceManager.GetString("Trusted Guidance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your message....
        /// </summary>
        public static string typeText {
            get {
                return ResourceManager.GetString("typeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAE Independent Climate Change Accelerators (UICCA).
        /// </summary>
        public static string UAE_Independent_Climate_Change_Accelerators__UICCA_ {
            get {
                return ResourceManager.GetString("UAE Independent Climate Change Accelerators (UICCA)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates to Policies.
        /// </summary>
        public static string Updates_to_Policies {
            get {
                return ResourceManager.GetString("Updates to Policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use of Information:.
        /// </summary>
        public static string Use_of_Information_ {
            get {
                return ResourceManager.GetString("Use of Information:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Conduct and Responsibilities.
        /// </summary>
        public static string User_Conduct_and_Responsibilities {
            get {
                return ResourceManager.GetString("User Conduct and Responsibilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Responsibilities:.
        /// </summary>
        public static string User_Responsibilities_ {
            get {
                return ResourceManager.GetString("User Responsibilities:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We reserve the right to update these policies at any time. Users will be notified of any changes on our website..
        /// </summary>
        public static string UTP {
            get {
                return ResourceManager.GetString("UTP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users are prohibited from engaging in any unlawful activities on our website. Any violation of these terms may result in the termination of services..
        /// </summary>
        public static string UUR1 {
            get {
                return ResourceManager.GetString("UUR1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We ensure top-notch experiences for every traveler..
        /// </summary>
        public static string We_ensure_top_notch_experiences_for_every_traveler_ {
            get {
                return ResourceManager.GetString("We ensure top-notch experiences for every traveler.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What you are looking for?.
        /// </summary>
        public static string What_you_are_looking_for_ {
            get {
                return ResourceManager.GetString("What you are looking for?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why choose us?.
        /// </summary>
        public static string Why_choose_us_ {
            get {
                return ResourceManager.GetString("Why choose us?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YAS HOLDING.
        /// </summary>
        public static string YAS_HOLDING {
            get {
                return ResourceManager.GetString("YAS HOLDING", resourceCulture);
            }
        }
    }
}
